### ISSUE TITLE
Consider adding a LICENSE file

### ISSUE THREAD

**Issue by soupglasses** [rengare/dotfiles#3]
Hi there!

I saw your awesome helper functions in [helpers.nix](https://github.com/rengare/dotfiles/blob/bc4c7907d06b378a361763506bdc9d1b62ea06fd/nix/helpers.nix) and i wanted to source them for myself. However, due to the missing license file, I cannot decipher what usage rights would be involved by sourcing your flake file, as it is uncleanly stated.

You may consider using an open source license, for example [MIT](https://github.com/git/git-scm.com/blob/main/MIT-LICENSE.txt), or making the file to state `All Rights Reserved <name>` if it is meant to only be source available.

Thank you!

**Comment by rengare** [comment]
@soupglasses thank you very much, license is added, its MIT

**Comment by soupglasses** [comment]
Do excuse me, but you seem to have written me as the copyright author for your project. Which is not correct. :sweat_smile: 

https://github.com/rengare/dotfiles/blob/bb737988a2f441876eb4c75b9062305af0b95f9e/LICENSE#L3

**Comment by rengare** [comment]
@soupglasses oh sorry, I copied your license file and forgot to change it :D, the update should be there
